sudo: required
services:
- docker
language: bash
script:
- export DOMOTICZ_VERSION=$(curl https://releases.domoticz.com/releases/downloads.php | grep -oP '\d.\d{4}' | tail -1)
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t gmaslowski/rpi-domoticz:$DOMOTICZ_VERSION .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker push gmaslowski/rpi-domoticz:$DOMOTICZ_VERSION
  fi
